language: python
dist: focal  # Use Ubuntu 20.04 (Focal Fossa)
python:
  - "3.10"   # Specify Python version

before_install:
  # Update system
  - sudo apt-get update

install:
  # Upgrade pip and install dependencies
  - python -m pip install --upgrade pip
  - pip install telebot pymongo aiohttp
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

script:
  # Make script executable and run it
  - chmod +x Spike.py
  - python Spike.py
